/// <reference path="../../typings/main.d.ts"/>
/// <reference path="../../node_modules/angular2/core.d.ts"/>
/// <reference path="../../node_modules/angular2/common.d.ts"/>
/// <reference path="../../node_modules/angular2/http.d.ts"/>
/// <reference path='./apiProxies/baseApiProxy.ts' /> 
/// <reference path='./apiProxies/accountApiProxy.ts' /> 
/// <reference path='./apiProxies/emailApiProxy.ts' /> 
/// <reference path='./apiProxies/profileApiProxy.ts' /> 
/// <reference path='./apiProxies/categoryApiProxy.ts' /> 
/// <reference path='./components/about/index.ts' /> 
/// <reference path='./components/account/forgotPassword.ts' />
/// <reference path='./components/account/index.ts' /> 
/// <reference path='./components/account/login.ts' />
/// <reference path='./components/account/register.ts' />
/// <reference path='./components/common/actionPanel.ts' /> 
/// <reference path='./components/common/detailPanel.ts' /> 
/// <reference path='./components/common/resultPanel.ts' /> 
/// <reference path='./components/inbox/index.ts' />
/// <reference path='./components/profile/edit.ts' />
/// <reference path='./components/profile/index.ts' />
/// <reference path='./components/search/filters.ts' />
/// <reference path='./components/search/index.ts' />
/// <reference path='./components/settings/details.ts' />
/// <reference path='./components/settings/index.ts' />
/// <reference path='./components/settings/result.ts' />
/// <reference path='./components/search/results.ts' />
/// <reference path='./constants/controllerConstants.ts' /> 
/// <reference path='./constants/errorConstants.ts' /> 
/// <reference path='./constants/serviceConstants.ts' /> 
/// <reference path='./directives/checkboxList.ts' />
/// <reference path='./models/_models.d.ts' />
/// <reference path="./services/searchService.ts" /> 
/// <reference path="./services/accountService.ts" /> 
/// <reference path="./utilities/httpConfigHelper.ts" /> 
/// <reference path="./utilities/objecthelper.ts" /> 